apiVersion: v1
kind: Service
metadata:
  name: python-katas-devops
  namespace: python-katas-devops
spec:
  type: NodePort
  selector:
    app: python-katas-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30020
