name: CI/CD - Python Katas

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # -------------------------
  # JOB 1: LINT
  # -------------------------
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install flake8

      - name: Lint code
        run: flake8 app tests

  # -------------------------
  # JOB 2: TEST + COVERAGE
  # -------------------------
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=app/domain --cov-report=term-missing --cov-fail-under=85

  # -------------------------
  # JOB 3: SECURITY (DEPENDENCIES)
  # -------------------------
  security-code:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project and security tools
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pip-audit bandit

      - name: Dependency vulnerability scan
        run: pip-audit

      - name: Static security scan
        run: bandit -r app

  # -------------------------
  # JOB 4: RELEASE (SEMVER)
  # -------------------------
  release:
    runs-on: ubuntu-latest
    needs: security-code

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  # -------------------------
  # JOB 5: DOCKER BUILD & PUSH
  # -------------------------
  docker:
    runs-on: ubuntu-latest
    needs: release

    if: github.event.name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: EXtract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            99diego/python-katas-devops:${{ env.VERSION }}
            99diego/python-katas.devops:latest
  
  # -------------------------
  # JOB 6: SECURITY (DOCKER IMAGE)
  # -------------------------
  security-image:
    runs-on: ubuntu-latest

    # Run only if the image was created correctly
    needs: docker

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      # Scan the Docker image for vulnerabilities
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: docker.io/99diego/python-kata-devops:${{ env.VERSION }}

          # Pipeline fails if there are vulnerabilities HIGH or CRITICAL
          exit-code: 1
          severity: CRITICAL,HIGH

