name: CI/CD - Python Katas

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Lint code
        run: flake8 app tests

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov --cov-report=term-missing --cov-fail-under=85

# -------------------------
  # JOB 3: SECURITY (PYTHON DEPENDENCIES)
  # -------------------------
  security-code:
    runs-on: ubuntu-latest

    # Only run if the tests passed
    needs: test

    steps:
      # Clone the repository
      - uses: actions/checkout@v4

      # Configure Python 3.12
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install pip-audit to scan vulnerabilities
      - name: Install pip-audit
        run: pip install pip-audit

      # Scan project dependencies
      # Fail if known CVEs are found        # ---> Common Vulnerabilities and Exposures
      - name: Run dependency scan
        run: pip-audit                      # ---> pip-audit checks packages installed and reports security issues

  # -------------------------
  # Job 4: RELEASE (SEMANTIC VERSIONING)
  # -------------------------
  release:
    runs-on: ubuntu-latest

    # Run only if there aren't critical vulnerabilities
    needs: security-code

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Necessary permissions to create tags, releases and notes  
    permissions:
      contents: write                        # ---> tags & releases
      issues: write                          # ---> comment / close issues
      pull-requests: write                   # ---> comment PR

    steps:
      # Clone the repository with the entire history (required to semantic-release)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0                     

      # Install Node.js (semantic-release is a Node tool)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install semantic-release and its plugins globally
      - name: Install Node dependencies
        run: npm ci 

      # Run semantic-release
      # Calculate the version based on commits and create the tag and release
      - name: Run semantic-release
        env:
          # GitHub automatic token to authenticate the action 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       # ---> allows the bot to execute the granted permissions
        run: npx semantic-release


  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            99diego/kata-devops-python:latest

